// Code generated by hertz generator.

package rbac

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rbacMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assignpermissiontoroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _assignroletouserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkpermissionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getallrolesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrolepermissionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserrolesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokepermissionfromroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revokerolefromuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
