// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID        int64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	Title     string     `gorm:"column:title;type:varchar(255);not null" json:"title"`
	Content   *string    `gorm:"column:content;type:text" json:"content"`
	AuthorID  int64      `gorm:"column:author_id;type:bigint unsigned;not null" json:"author_id"`
	Status    int32      `gorm:"column:status;type:tinyint;not null;comment:0=draft, 1=published, 2=archived" json:"status"` // 0=draft, 1=published, 2=archived
	Slug      *string    `gorm:"column:slug;type:varchar(255)" json:"slug"`
	Views     int64      `gorm:"column:views;type:bigint unsigned;not null" json:"views"`
	IsDeleted int32      `gorm:"column:is_deleted;type:tinyint;not null;comment:0=active, 1=deleted" json:"is_deleted"` // 0=active, 1=deleted
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
