// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string     `gorm:"column:id;type:varchar(36);primaryKey" json:"id"`
	Username     string     `gorm:"column:username;type:varchar(50);not null" json:"username"`
	Email        *string    `gorm:"column:email;type:varchar(255)" json:"email"`
	PasswordHash string     `gorm:"column:password_hash;type:varchar(255);not null" json:"password_hash"`
	FullName     *string    `gorm:"column:full_name;type:varchar(100)" json:"full_name"`
	Phone        *string    `gorm:"column:phone;type:varchar(20)" json:"phone"`
	Status       int32      `gorm:"column:status;type:tinyint;not null;default:1;comment:1=active, 0=inactive, -1=banned" json:"status"` // 1=active, 0=inactive, -1=banned
	CreatedAt    time.Time  `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    *time.Time `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	LastLoginAt  *time.Time `gorm:"column:last_login_at;type:datetime" json:"last_login_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
