// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	rbac "github.com/ocybers-dev/ocybers/biz/router/rbac"
	user "github.com/ocybers-dev/ocybers/biz/router/user"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	rbac.Register(r)

	user.Register(r)
}
